spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MichaelMChan/robin
#server:
#  port: 1201
server:
  port: 7001

#encrypt.key: didispace

eureka.client.serviceUrl.defaultZone: http://localhost:1001/eureka/